### ISSUE TITLE
Support for running test/describe by name

### ISSUE THREAD

**Issue by Maxim-Filimonov** [influxdata/mix_test_interactive#47]
Hi,
Thanks for the great tool!
I'd been to contribute if you think it's a good idea to add functionality this functionality  from mix test:
```
mix test --exclude test --include 'test:test file upload on upload for all sets submit for all' file_upload_test.exs
```
Not sure if we can get list of all tests somehow - maybe with test.trace?  or maybe mix.test provides some facility to do so.

**Comment by randycoulman** [comment]
I'd like to support the `include`/`exclude`/`only` arguments, but haven't been able to come up with a good way to do it because of the ordering dependency between them - it matters if you exclude first or include first.  I tend not to use tags, so I'm not sure what patterns people like to use. If you have any ideas there, I'd be interested in your thoughts or contribution.

Does `mix test` support running tests by name? I don't see that in the docs, but that doesn't mean it doesn't work.

I haven't found a way to get a list of tests from `mix test` without duplicating its internal code. Plus, the list can change on every run, depending on what files you've changed.  I'm not familiar with `test.trace`, though. Do you have a link to something that describes it? I know about `mix test --trace`, but I'm not sure that's what you mean.

**Comment by randycoulman** [comment]
I just remembered that I've already written an issue up for the `include/`exclude`/`only` feature; see #31.

**Comment by jfpedroza** [comment]
> Does mix test support running tests by name?

Yes, like the issue mentions. `ExUnit` generates a `test` tag with a value that looks like `test #{describe name} #{test name}` so you can do something like `mix test --only 'test:test name' test_file.exs`. Passing the test file is actually not necessary, but it will speed things up and will run only one test if another file also defines the name.

> I'm not familiar with test.trace, though.

I don't think that's a thing.

**Comment by Maxim-Filimonov** [comment]
Closing as duplicate of #31
